import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      >
        <nav className="fixed top-0 left-0 w-full z-50 flex items-center gap-8 px-8 h-16 bg-white border-b border-gray-200 shadow-sm">
          <span className="font-bold text-xl tracking-wide text-blue-600 mr-8 select-none">
            MedMate
          </span>
          <a href="/dashboard" className="text-gray-800 hover:text-blue-600 transition-colors py-2 px-2 font-medium">Dashboard</a>
          <a href="/record-new-case" className="text-gray-800 hover:text-blue-600 transition-colors py-2 px-2 font-medium">Record New Case</a>
          <a href="/soap-note" className="text-gray-800 hover:text-blue-600 transition-colors py-2 px-2 font-medium">SOAP Note</a>
          <a href="/case-feedback" className="text-gray-800 hover:text-blue-600 transition-colors py-2 px-2 font-medium">Case Feedback</a>
          <a href="/ai-assistant" className="text-gray-800 hover:text-blue-600 transition-colors py-2 px-2 font-medium">AI Assistant</a>
          <a href="/case-library" className="text-gray-800 hover:text-blue-600 transition-colors py-2 px-2 font-medium">Case Library</a>
        </nav>
        <div className="pt-20 px-4 md:px-8">
          {children}
        </div>
      </body>
    </html>
  );
}
